### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by brunowego** [trwired/baseline-overlay#1]
You have a nice plugin here, thanks for share!

**Comment by trwired** [comment]
Thanks! Glad to know someone finds it interesting/useful!

**Comment by brunowego** [comment]
A tip, take a look at http://basehold.it/, perhaps take the same way of this can do more powerful for your project.

**Comment by trwired** [comment]
I created this project because I needed to contain the grid to a particular element, as opposed to overlaying it on top of the entire page, like the one you linked does. This makes my plugin more flexible.
